CREATE DATABASE IF NOT EXISTS test DEFAULT CHARSET utf8 DEFAULT COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS test@localhost IDENTIFIED BY 'secret';
GRANT SELECT, INSERT, UPDATE, DELETE ON test.* TO test@localhost;
FLUSH PRIVILEGES;
USE test;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    pass VARCHAR(256) NOT NULL,

    PRIMARY KEY (id),
    UNIQUE INDEX (name)
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    slug VARCHAR(128) NOT NULL,

    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INTEGER UNSIGNED NOT NULL,
    product_id INTEGER UNSIGNED NOT NULL,
    value TEXT DEFAULT NULL,

    PRIMARY KEY (id),
    UNIQUE INDEX (product_id, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ratings (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INTEGER UNSIGNED NOT NULL,
    product_id INTEGER UNSIGNED NOT NULL,
    value TINYINT UNSIGNED DEFAULT NULL,

    PRIMARY KEY (id),
    UNIQUE INDEX (product_id, user_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE
);
